#! /bin/sh

pgrep -x sxhkd || sxhkd &

pgrep -x polybar || sh ~/.config/polybar/launch.sh &

pgrep -x greenclip || greenclip daemon &

feh ~/Pictures/wallpaper.jpeg

pgrep -x picom || picom -b &

xsetroot -cursor_name left_ptr &

pgrep -x xfce4-power-manager || xfce4-power-manager &

xmodmap -e 'clear Lock' -e 'keycode 0x42 = v' &