#!/bin/sh

### Configuración Inicial de BSPWM ###

# Crear escritorios en el monitor principal
bspc monitor -d MAIN CODE MEDIA TOR VPN

# Reglas para escritorios y aplicaciones
# MAIN: Libre de reglas, puedes abrir cualquier cosa.
# CODE: Espacio para VSCode o VSCodium.
bspc rule -a code.desktop=^2
# MEDIA: Sin reglas, similar a MAIN.
# TOR: Uso principal para Tor Browser, pero sin limitar otros programas.
bspc rule -a 'Tor Browser' desktop=^4
# VPN: Ejecutar Alacritty por defecto, pero abierto a otros programas.
bspc rule -a Alacritty desktop=^5

# Configuración de límites de ventanas
# Un máximo de 3 ventanas por escritorio.
bspc config split_ratio 0.5
for desk in {1..5}; do
    bspc desktop "^$desk" --set max_windows 3
done

# Configuración de bordes y gaps
bspc config window_gap 10
bspc config border_width 4
bspc config focused_border_color "#8C2B32"  # Violeta brillante.
bspc config normal_border_color "#5D5C31"  # Color para ventanas no enfocadas.

# Configurar ventanas flotantes (Thunar/Dolphin por defecto)
bspc rule -a Thunar state=floating
bspc rule -a Dolphin state=floating

### Acciones Dinámicas ###

# Ejecutar picom (compositor) con configuración personalizada
picom --config ~/.config/picom/picom.conf &

# Ejecutar feh con fondo de pantalla inicial
feh --bg-scale ~/.config/feh/wallpapers/main.jpeg &